/*!
 * Image (upload) dialog plugin for Editor.md
 *
 * @file        file-dialog.js
 * @author      dup4
 * @version     2.0.0
 * @updateTime  2020-05-25
 * {@link       https://github.com/pandao/editor.md}
 * @license     MIT
 */
!function(){var e=function(e){e.fn.fileDialog=function(){var e,t=this,i=this.cm,a=this.lang,l=this.editor,n=this.settings,o=(i.getCursor(),i.getSelection()),d=a.dialog.file,r=this.classPrefix,f=r+"file-dialog";i.focus();var s=function(t){e.find("."+r+"dialog-mask")[t?"show":"hide"]()},c=function(i){if(i){if(s(!0),""===i.name)return alert(d.uploadFileEmpty),s(!1),!1;var a=new FormData;a.append("file",i);var l=n.uploadURL+(n.uploadURL.indexOf("?")>=0?"&":"?")+"&id="+t.id;$.ajax({type:"POST",url:l,data:a,cache:!1,contentType:!1,processData:!1,success:function(t){s(!1),1===t.success?e.find("[data-url]").val(t.url):alert(t.message)},complete:function(){s(!1)},error:function(e,t){s(!1)}})}};if(l.find("."+f).length<1){var u=(new Date).getTime(),p=(n.fileUpload?'<form class="'+r+'form">':'<div class="'+r+'form">')+"<label>"+d.url+'</label><input type="text" data-url />'+(n.fileUpload?'<div class="'+r+'file-input"><input type="file" name="'+r+'upload-file" /><input type="submit" value="'+d.uploadButton+'" /></div>':"")+"<br/><label>"+d.alt+'</label><input type="text" value="'+o+'" data-alt /><br/>'+(n.fileUpload?"</form>":"</div>");if((e=this.createDialog({title:d.title,width:n.fileUpload?465:380,height:214,name:f,content:p,mask:n.dialogShowMask,drag:n.dialogDraggable,lockScreen:n.dialogLockScreen,maskStyle:{opacity:n.dialogMaskOpacity,backgroundColor:n.dialogMaskBgColor},buttons:{enter:[a.buttons.enter,function(){var e=this.find("[data-url]").val(),t=this.find("[data-alt]").val();if(""===e)return alert(imageLang.imageURLEmpty),!1;return i.replaceSelection("\n\n["+(""===t?"附件描述":t)+"]("+e+")\n\n"),this.hide().lockScreen(!1).hideMask(),this.remove(),!1}],cancel:[a.buttons.cancel,function(){return this.hide().lockScreen(!1).hideMask(),this.remove(),!1}]}})).attr("id",r+"file-dialog-"+u),!n.fileUpload)return;var h=e.find('[name="'+r+'upload-file"]');h.bind("change",(function(){return c(h[0].files[0])}))}(e=l.find("."+f)).find('[type="text"]').val(""),e.find('[type="file"]').val(""),this.dialogShowMask(e),this.dialogLockScreen(),e.show(),t.uploadFile.length>0&&c(t.uploadFile.shift())}};"function"==typeof require&&"object"==typeof exports&&"object"==typeof module?module.exports=e:"function"==typeof define?define.amd?define(["editormd"],(function(t){e(t)})):define((function(t){var i=t("./../../editormd");e(i)})):e(window.editormd)}();